# Generated by Django 5.2.5 on 2025-08-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_remove_room_occupied_seats_alter_payment_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='hostel.room'),
        ),
    ]
